# Generated by Django 2.1.7 on 2019-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('image', models.FileField(upload_to='posts_images/%s/')),
                ('created_at', models.DateTimeField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
